### ISSUE TITLE
(From TPW2) Unowned Scanner unintended renaming?

### ISSUE THREAD

**Issue by Vectorial1024** [mewosmith/TeleportationWarsAlpha#4]
Currently, the Unowned Scanner scans the current sector for any unowned objects (ships, the PHQ, etc.), and rename them as "Unknown Contact" for easier identification.

However, it is found that the Scanner also renames Aqueducts and Data Vaults (both are always ownerless) to "Unknown Contact", which prevented Betty from playing their respective announcer sound effect.

**Comment by mewosmith** [comment]
Find Ownerless Scan no longer works this way in TPWAR 3.
